### ISSUE TITLE
刚哥，能优化下内存占用吗

### ISSUE THREAD

**Issue by 8w7BG7l2nMNm0g09FZzAz3zlt** [liues1992/php-protobuf-generator#3]
### 1.现象
随着L部门的业务发展，proto越来越多，generator分配的mem也水涨船高，直到今天出现了这个2333
![image](https://user-images.githubusercontent.com/16574870/88022862-9bd6ca80-cb62-11ea-9add-aceae5de307f.png)

### 2.php配置
默认memory_limit = 128M，然后exhausted了

### 3.临时解决
调大memory_limit

### 4.顺便问声好
万事如意，身体健康：）

**Comment by liues1992** [comment]
这个.... 我有时间尝试一下。
占128M内存其实还好，调大memory_limit可以作为永久措施。毕竟这只是生成代码时在本地运行，不影响生产环境。
祝你生活愉快！

**Comment by 8w7BG7l2nMNm0g09FZzAz3zlt** [comment]
> 这个.... 我有时间尝试一下。
> 占128M内存其实还好，调大memory_limit可以作为永久措施。毕竟这只是生成代码时在本地运行，不影响生产环境。
> 祝你生活愉快！

哈哈，其实我就一说，毕竟白嫖的tool
